fix: shell check on finish release

diff --git a/.github/workflows/finish-release.yml b/.github/workflows/finish-release.yml
--- a/.github/workflows/finish-release.yml
+++ b/.github/workflows/finish-release.yml
@@ -88,28 +88,34 @@ jobs:
     env:
       GH_TOKEN: ${{ github.token }}
     steps:
-      - name: Merge release PR
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Finalise PR
         run: | 
           export PR_ID=$(gh pr list --state "open" --author "app/github-actions" --search "release"  --json "number" --jq '. | first | .number')
-          if [ ! -z $PR_ID ]; then
-          ## seting up git
+          if [ -n "$PR_ID" ]; then
+            ## seting up git
             git config user.name "GitHub Actions Bot"
             git config user.email "<>"
 
-            # # create release branch
+            # create release branch
             git pull # make sure git doesn't reject our push becasue of unknown refs
-            gh pr merge $PR_ID
+            gh pr merge "$PR_ID"
             git pull
             git checkout main
             export RELEASE_VERSION=$(grep "version" hydromt/__init__.py | cut -d= -f 2 | tr -d "\" ")
-            if [ ! -z $RELEASE_VERSION ]; then
+            if [ -n "$RELEASE_VERSION" ]; then
               exit 1 # somthing went very wrong
             fi
-            git tag v$NEW_VERSION
+            git tag "v$NEW_VERSION"
             # post release stuff so we don't forget
             sed -i "s/v$RELEASE_VERSION/Unreleased\n==========\n\nNew\n---\n\nChanged\n-------\n\nFixed\n-----\n\nDeprecated\n----------\n\nv$RELEASE_VERSION/" docs/changelog.rst
             sed -i 's/__version__.*=.*"\(.*\)".*/__version__ = "\1.dev0"/' hydromt/__init__.py
-
+            
             git add hydromt/__init__.py docs/changelog.rst            
             git commit -m "Post release"
             git push main origin
+          else
+            echo "could not find release PR"
+            exit 1
+          fi
