add prepare release code to release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,66 +29,90 @@ jobs:
     defaults:
       run:
         shell: bash -l {0}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, windows-latest]
-        # python-version: ['3.10','3.11']
-        python-version: ['3.10']
-        include:
-          - os: windows-latest
-            mamba-path: C:\\Users\\runneradmin\\miniconda3\\condabin\\mamba
-            miniconda-path: C:\Users\runneradmin\miniconda3
-            pycache-path: C:\Users\runneradmin\pycache
-          - os: ubuntu-latest
-            miniconda-path: ~/miniconda3
-            mamba-path: ~/miniconda3/condabin/mamba
-            pycache-path: ~/pycache
     name: py ${{ matrix.python-version }} (${{ matrix.os }})
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-24.04 # latest LTS release
     concurrency:
-      group: ${{ github.workflow }}${{ matrix.os }}-${{ matrix.python-version }}-${{ github.ref }}
-      cancel-in-progress: true
+      group: NEW_RELEASE
+      cancel-in-progress: false # don't abort while we might be creating a PR or something
     steps:
 
       - uses: actions/checkout@v4
 
-      # we need environment.yml to see if we have a cache hit
-      - name: Generate env spec
-        run: pip install tomli && python make_env.py test,io,extra -p ${{ matrix.python-version}} -n hydromt
-
-      - name: load from cache
-        id: cache
-        uses: actions/cache/restore@v4
-        with:
-          path: |
-            ${{ matrix.miniconda-path }}
-            ${{ matrix.pycache-path }}
-          # the below two settings mean we'll always restore the cache
-          # but the cache hit output can tell us if we have to update afterwards
-          key: test-${{ matrix.os }}-py${{ matrix.python-version }}-${{ hashFiles('environment.yml')  }}
-          restore-keys: |
-            test-${{ matrix.os }}-py${{ matrix.python-version }}
-            test-${{ matrix.os }}
-
-      - name: Fail on no cache restore
-        if: steps.cache.outputs.cache-matched-key == ''
+      - name: setup release PR
         run: |
-          echo "Failed to restore any cache. exiting..."
-          exit 1
 
-      # by avoiding the mamba setup stage by loading it from cache instead we save
-      # a lot of setup time, but we do have to do our own PATH management
-      # hence the exports
-      - name: Update environment
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: |
-          ${{ matrix.miniconda-path }} env update -n hydromt -f environment.yml
+          set -e
+          # parsing of current version
+          export CURRENT_VERSION=$(grep "version" hydromt/__init__.py | cut -d= -f 2 | tr -d "\" ")
+          export CURRENT_MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f 1)
+          export CURRENT_MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f 2)
+          export CURRENT_PATHCH=$(echo $CURRENT_VERSION | cut -d'.' -f 3)
 
-      - name: Test
-        run: |
-          ${{ matrix.mamba-path }} run -n hydromt python -m pytest --verbose --cov=hydromt --cov-report xml
+          BUMP="minor"
 
-      - name: Setup tmate session
-        if: ${{ failure() }}
-        uses: mxschmitt/action-tmate@v3
+          ## calculate new release number
+          case $BUMP in
+
+          "patch")
+          	export NEW_VERSION="$CURRENT_MAJOR.$CURRENT_MINOR.$((CURRENT_PATHCH + 1))"
+          	;;
+
+          "minor")
+          	export NEW_VERSION="$CURRENT_MAJOR.$(($CURRENT_MINOR + 1)).0"
+          	;;
+
+          "major")
+          	export NEW_VERSION="$((CURRENT_MAJOR + 1)).0.0"
+          	;;
+
+          *)
+          	echo "invalid bump"
+          	exit 1
+          	;;
+          esac
+
+          ## seting up git
+          # git config user.name "GitHub Actions Bot"
+          # git config user.email "<>"
+
+          # create release branch
+          # git checkout -b "release/v$NEW_VERSION"
+
+          # update version in python file
+          # sed -i "s/.*__version__.*/__version__ = \"$NEW_VERSION\"/" hydromt/__init__.py
+
+          sed -i "s/.*__version__.*/__version__ = \"$NEW_VERSION\"/" docs/changelog.rst
+          export NEW_CHANGELOG_HEADER="v$NEW_VERSION ($(date -I))"
+          export NEW_HEADER_UNDERLINE=$(printf '=%.0s' $(seq 1 $(echo $NEW_CHANGELOG_HEADER | awk '{print length}')))
+
+          # update chagnelog with new header
+          sed -i "/Unreleased/{s/Unreleased/$NEW_CHANGELOG_HEADER/;n;s/=*/$NEW_HEADER_UNDERLINE/}" docs/changelog.rst
+
+          # update switcher.json while maintianing the correct order with some black jq incantations. I'll try and explain below
+          cat docs/switcher.json | jq "map(select(.version != \"latest\")) | . + [{\"name\":\"v$NEW_VERSION\",\"version\":\"$NEW_VERSION\",\"url\":\"https://deltares.github.io/hydromt/v$NEW_VERSION/\"}] | sort_by(.version|split(\".\")|map(tonumber)) | . + [{\"name\":\"latest\",\"version\":\"latest\",\"url\":\"https://deltares.github.io/hydromt/latest\"}]" >tmp.json
+
+          # map(select(.version != \"latest\"))
+          # removes the "latest" entry, since we'll need to sort numerically by number in a later step
+
+          #| . +
+          # take the result of the previous operation and add the following array to it
+
+          # [{\"name\":\"v$NEW_VERSION\",\"version\":\"$NEW_VERSION\",\"url\":\"https://deltares.github.io/hydromt/v$NEW_VERSION/\"}]
+          # an array with the new entry we want to add
+
+          # sort_by(.version|split(\".\")|map(tonumber))
+          # take the array, split the version field by the "." char and make numbers out of the components. then sort the whole array by these numbers
+          # this is why we had to remove the latest field earlier,
+          # otherwise the number conversion would fail here.
+
+          #| . + [{\"name\":\"latest\",\"version\":\"latest\",\"url\":\"https://deltares.github.io/hydromt/latest\"}]
+          # add teh latest field back in at the end
+
+          # avoid race conditions by using a tmp file
+          mv tmp.json docs/switcher.json
+
+          git add .
+          git commit -m "prepare for release v$NEW_VERSION"
+          git push
+
+          gh pr create -B "main" -H "release/v$NEW_VERSION" -t "Release v$NEW_VERSION" -T ".github/templates/release_pr.md"
